# shellcheck shell=bash
# Phase 12.3 PML A/B common runner — SOURCED by the three pml sbatch variants
# (spatial_dyn_pml_on / _off / _bigbox_ref).  NOT a standalone job.
#
# Provides the shared Frontera boilerplate (modules, seas-mfem root resolve,
# ZFP plugin, config.mk feature gates, pre-built binary check) plus a
# `run_pml_driver` function that the caller invokes with mode-specific args
# (e.g. --pml / --tfinal).  The caller sets these before sourcing:
#   PML_MODE      : on | off | bigbox  (banner label only)
#   (optional) SAFS_CONFIG, SAFS_MESH, SAFS_TFINAL, SAFS_CFL, SAFS_RESTART
#
# Mirrors the boilerplate of the existing
# spatial_dyn_slipweakening_*_safs.sbatch jobs verbatim so the PML variants run
# in the same environment.

export LC_ALL=C
export LANG=C

# V_max / [DIAG-SIGN] trace ON — the PML-effectiveness signal that
# pml_reflection_metrics.py parses.  Verbose frame/macro OFF.
export SEAS_DIAG_SLIP="${SEAS_DIAG_SLIP:-0}"
export SEAS_DIAG_FRAME="${SEAS_DIAG_FRAME:-0}"
export SEAS_DIAG_MACRO="${SEAS_DIAG_MACRO:-0}"
export SEAS_DIAG_BLOWUP="${SEAS_DIAG_BLOWUP:-1}"

module load intel/19.1.1
module load impi/19.0.9
module load hypre/2.31.0
module load mumps/5.3
module load parmetis
module load petsc/3.15
module load fftw3/3.3.8

export LD_LIBRARY_PATH="${TACC_HYPRE_LIB}:${TACC_PARMETIS_LIB}:${TACC_MUMPS_LIB}:${TACC_PETSC_LIB}:${TACC_FFTW3_LIB}:${LD_LIBRARY_PATH}"

# Resolve seas-mfem root by walking UP until miniapps/seas/Makefile is found.
SEAS_MFEM_ROOT="${SEAS_MFEM_ROOT:-${SLURM_SUBMIT_DIR}}"
_walk_up_dir="${SEAS_MFEM_ROOT}"
for _ in 0 1 2 3 4 5; do
    if [[ -f "${_walk_up_dir}/miniapps/seas/Makefile" ]]; then
        SEAS_MFEM_ROOT="$(cd "${_walk_up_dir}" && pwd)"
        break
    fi
    _walk_up_dir="${_walk_up_dir}/.."
done
if [[ ! -f "${SEAS_MFEM_ROOT}/miniapps/seas/Makefile" ]]; then
    echo "ERROR: cannot locate seas-mfem root from SLURM_SUBMIT_DIR="
    echo "  ${SLURM_SUBMIT_DIR}.  Set SEAS_MFEM_ROOT explicitly via"
    echo "  sbatch --export=ALL,SEAS_MFEM_ROOT=/path/to/seas-mfem ..."
    exit 1
fi
cd "${SEAS_MFEM_ROOT}"

# ZFP HDF5 filter plugin (libh5zzfp.so), required for --paraview-*-zfp-tol.
H5Z_ZFP_BUILT_DIR="${SEAS_MFEM_ROOT}/extern/h5z-zfp/install"
if [[ -e "${H5Z_ZFP_BUILT_DIR}/plugin/libh5zzfp.so" ]]; then
    export HDF5_PLUGIN_PATH="${H5Z_ZFP_BUILT_DIR}/plugin:${HDF5_PLUGIN_PATH:-}"
else
    echo "ERROR: ZFP plugin not found at ${H5Z_ZFP_BUILT_DIR}/plugin/libh5zzfp.so"
    echo "       Build it on Frontera (bash build_frontera.sh) or drop the"
    echo "       --paraview-*-zfp-tol flags from run_pml_driver."
    exit 1
fi

grep -q '^MFEM_USE_PETSC *= YES'  config/config.mk || { echo "ERROR: no PETSc"; exit 1; }
grep -q '^MFEM_USE_MUMPS *= YES'  config/config.mk || { echo "ERROR: no MUMPS"; exit 1; }
grep -q '^MFEM_USE_HDF5 *= YES'   config/config.mk || { echo "ERROR: no HDF5"; exit 1; }
grep -q '^MFEM_USE_H5Z_ZFP *= YES' config/config.mk || { echo "ERROR: no H5Z_ZFP"; exit 1; }

cd miniapps/seas
# No in-job build (avoids the relink race when sibling jobs run concurrently);
# the binary must be pre-built by spatial_dyn_build_safs.sbatch / a login make.
if [[ ! -x ./seas_spatial_dyn_driver ]]; then
    echo "ERROR: ./seas_spatial_dyn_driver not found/executable in $(pwd)."
    echo "       Build it FIRST: sbatch miniapps/seas/jobs/safs/spatial_dyn_build_safs.sbatch"
    exit 1
fi

SAFS_ROOT=safs/project_7.0_alternative
# Default = the LSW Dc2 (+ sigma_n floor) config used by the reflection study;
# override with SAFS_CONFIG (e.g. the rate-state config for an RS PML run).
CONFIG_TOML="${SAFS_CONFIG:-${SAFS_ROOT}/config/spatial_friction_slip_weakening_safs_projected_stress_resolution_Dc2.toml}"
if [[ ! -f "${CONFIG_TOML}" ]]; then
    echo "ERROR: config not found: $(pwd)/${CONFIG_TOML}"
    exit 1
fi

# Mesh: default = the sliver-repaired triq mesh; bigbox variant overrides with
# a deeper/wider mesh via SAFS_MESH (it is generated by run_z0cut_meshing.py
# --pad-* and scp'd in — the .msh is gitignored).
TRIQ_MESH="${SAFS_ROOT}/experimental_mesh_refinement/safs_fault_box_nwcut_500m_lcfar3000_z0embed_triq.msh"
MESH="${SAFS_MESH:-${TRIQ_MESH}}"
if [[ ! -f "${MESH}" ]]; then
    echo "ERROR: mesh not found: $(pwd)/${MESH}"
    echo "       (.msh is gitignored — scp it to the path above before submitting.)"
    exit 1
fi

# IMPORTANT: [mesh].lc_far_m must be set in the config (or pass --pml-thickness)
# so the driver can DERIVE the PML thickness (pml_cells * lc_far).  The triq
# mesh above is lcfar=3000 m; the default --pml-cells 4 => L_pml = 12 km
# (plan §12.0).  run_pml_driver passes --pml-thickness explicitly when
# SAFS_PML_THICKNESS is set, bypassing the lc_far derivation.

LOG_DIR="${SEAS_MFEM_ROOT}/miniapps/seas/jobs/safs"
mkdir -p "${LOG_DIR}"

# run_pml_driver <output-tag> <extra driver args...>
#   Builds OUT/LOG from the tag + SLURM_JOB_ID, echoes a provenance banner, runs
#   ibrun, then checks the run RC and (for PML modes) the "PML: ACTIVE" banner.
run_pml_driver() {
    local tag="$1"; shift
    local OUT="${SEAS_MFEM_ROOT}/miniapps/seas/safs/safs_dyn_${tag}_${SLURM_JOB_ID}"
    local LOG="${LOG_DIR}/spatial_dyn_${tag}_${SLURM_JOB_ID}.log"
    mkdir -p "${OUT}"

    local CFL_ARG=""; [[ -n "${SAFS_CFL:-}" ]] && CFL_ARG="--cfl ${SAFS_CFL}"
    local RESTART_ARG=""; [[ -n "${SAFS_RESTART:-}" ]] && RESTART_ARG="--restart ${SAFS_RESTART}"

    echo "Git commit:  $(git rev-parse HEAD)"
    echo "Git branch:  $(git rev-parse --abbrev-ref HEAD)"
    echo "PML mode:    ${PML_MODE:-?}"
    echo "Output dir:  ${OUT}"
    echo "Log file:    ${LOG}"
    echo "Mesh:        ${MESH}"
    echo "Config:      ${CONFIG_TOML}"
    echo "Driver args: $*"

    ibrun ./seas_spatial_dyn_driver \
        --config "${CONFIG_TOML}" \
        --mesh   "${MESH}" \
        --no-sidecar-material \
        ${CFL_ARG} \
        ${RESTART_ARG} \
        --paraview \
        --paraview-fault-hdf5 \
        --paraview-fault-zfp-tol 1.0e-12 \
        --paraview-max-snapshots 400 \
        --print-derived \
        --checkpoint-every 2000 \
        --output-dir "${OUT}" \
        "$@" \
        > "${LOG}" 2>&1
    local RC=$?

    if [[ "${PML_MODE}" == "on" ]]; then
        if grep -q 'PML: ACTIVE' "${LOG}"; then
            echo "pml_banner: ACTIVE  ($(grep -m1 'PML: ACTIVE' "${LOG}"))"
        else
            echo "WARNING: '--pml' set but no 'PML: ACTIVE' banner in ${LOG} —"
            echo "         the PML may NOT have been constructed.  Inspect the log."
        fi
    fi

    echo "driver_rc=${RC} — log: ${LOG}"
    echo "Next: parse V_max(t) with"
    echo "  python3 ${SAFS_ROOT}/spatial/code/scripts/pml_reflection_metrics.py --ab <ON.log> <OFF.log>"
    return ${RC}
}
