"""test_mesh_quality.py — Q1/Q2 + embedding + free-surface gates for
the six target SAFS NW-cut meshes.

PLAN_mesh_quality.md Phase 4 — verification harness.

Each test skips with `pytest.skip(...)` if its target mesh file is not
on disk (so a fresh checkout passes).  Once the meshes have been
regenerated by Phase 5 of the plan, every test must pass.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import meshio
import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from check_mesh_quality import (   # noqa: E402
    _extract_blocks,
    check_mesh_quality,
)

MSH_DIR = (HERE.parent / "results" / "msh").resolve()

TARGET_MESHES = [
    "safs_fault_box_nwcut_500m_zgraded.msh",
    "safs_fault_box_nwcut_1000m_zgraded.msh",
    "safs_fault_box_nwcut_2000m_zgraded.msh",
    "safs_fault_box_nwcut_500m_lcfar3000.msh",
    "safs_fault_box_nwcut_1000m_lcfar3000.msh",
    "safs_fault_box_nwcut_2000m_lcfar3000.msh",
]


def _msh_path(name: str) -> Path:
    p = MSH_DIR / name
    if not p.is_file():
        pytest.skip(f"mesh not built: {p}")
    return p


# ---------------------------------------------------------------------
# Q1 — minimum bulk tet edge length
# ---------------------------------------------------------------------

@pytest.mark.parametrize("mesh_name", TARGET_MESHES)
def test_q1_min_edge_target_meshes(mesh_name):
    """Bulk tet min edge >= 100 m for every target mesh."""
    p = _msh_path(mesh_name)
    r = check_mesh_quality(p)
    assert r["q1_pass"], (
        f"{mesh_name}: tet_emin={r['tet_emin']:.2f} m below 100 m floor; "
        f"violations: {r['violations']}")


# ---------------------------------------------------------------------
# Q2 — Joe-Liu eta floor for every bulk tet
# ---------------------------------------------------------------------

@pytest.mark.parametrize("mesh_name", TARGET_MESHES)
def test_q2_eta_floor_target_meshes(mesh_name):
    """eta_min > 0.1 for every target mesh (no slivers)."""
    p = _msh_path(mesh_name)
    r = check_mesh_quality(p)
    assert r["q2_pass"], (
        f"{mesh_name}: eta_min={r['eta_min']:.4f} <= 0.1 floor; "
        f"violations: {r['violations']}")


# ---------------------------------------------------------------------
# Free-surface invariant: mesh_zmax == 0 exactly
# ---------------------------------------------------------------------

@pytest.mark.parametrize("mesh_name", TARGET_MESHES)
def test_freesurface_invariant(mesh_name):
    """The mesh's top face must sit at z = 0 exactly (geoid)."""
    p = _msh_path(mesh_name)
    r = check_mesh_quality(p)
    assert r["mesh_zmax"] == 0.0, (
        f"{mesh_name}: mesh_zmax={r['mesh_zmax']} != 0.0 "
        "(violates free-surface invariant -- see meshing/README.md)")


# ---------------------------------------------------------------------
# Fault embedding: every Physical Surface 101 triangle must coincide
# with a face shared by exactly two bulk tetrahedra.
# ---------------------------------------------------------------------

@pytest.mark.parametrize("mesh_name", TARGET_MESHES)
def test_fault_embedded(mesh_name):
    """Every fault tri is shared by exactly 2 bulk tets (interior fault)."""
    p = _msh_path(mesh_name)
    m = meshio.read(str(p))
    tetra, fault_tri, _ = _extract_blocks(m)
    assert fault_tri is not None, (
        f"{mesh_name}: no Physical Surface 101 (fault) triangles found")

    # Build a hash of every internal tet face -> number of tets sharing it.
    local_faces = [(1, 2, 3), (0, 2, 3), (0, 1, 3), (0, 1, 2)]
    face_to_count = defaultdict(int)
    for t in tetra:
        for lf in local_faces:
            key = tuple(sorted((int(t[lf[0]]),
                                int(t[lf[1]]),
                                int(t[lf[2]]))))
            face_to_count[key] += 1

    unmatched = 0
    bad_mult = 0
    for tri in fault_tri:
        key = tuple(sorted((int(tri[0]), int(tri[1]), int(tri[2]))))
        mult = face_to_count.get(key, 0)
        if mult == 0:
            unmatched += 1
        elif mult != 2:
            bad_mult += 1
    assert unmatched == 0, (
        f"{mesh_name}: {unmatched}/{len(fault_tri)} fault triangles do "
        "not match any tet face (fault NOT embedded in bulk)")
    assert bad_mult == 0, (
        f"{mesh_name}: {bad_mult}/{len(fault_tri)} fault triangles are "
        "not shared by exactly 2 tets (fault is partially on the "
        "domain boundary)")
