// SAFS realistic-geometry mesh — assembled from CFM .ts files (cleaned to
// per-fault ASCII STL by ts_to_stl.py).  See miniapps/seas/safs/PLAN.md
// and PLAN_origin.md / PLAN_domain.md for the full design, and PLAN.md
// Phase 4 + the smoke-test plan for why the fault is *embedded* (not
// fragmented) — Gmsh's CreateGeometry / BooleanFragments do not promote
// discrete STL surfaces to OCC NURBS in our 4.13.x kernel, so the
// embedded-discrete fallback is the production path.
//
// Local frame (NOT UTM):
//   X = UTM Easting  - 500_000      (origin in UTM Zone 11N)
//   Y = UTM Northing - 3_765_000
//   Z = elevation, positive up; free surface at z = 0
//
// Physical groups (BP5-compatible, exactly as bp5_v2.geo):
//   1 = xm (Dirichlet)        2 = xp (Dirichlet)
//   3 = yp (Dirichlet)        4 = ym (Dirichlet)
//   5 = ztop (Natural)        6 = zbot (Natural)
//  10 = bulk volume          100 = fault (ALL CFM faults unified)
//
// All STLs are merged via Include "safs_includes.geo" — that file is
// generated by generate_safs_mesh.py from the user-supplied --include-fault
// list, so this .geo is independent of which subset of faults is meshed.

SetFactory("OpenCASCADE");

// --- Domain box (driver overrides via -setnumber) ---
DefineConstant[ x_min = {-150000, Name "Box xmin (m, local)"} ];
DefineConstant[ x_max = { 150000, Name "Box xmax (m, local)"} ];
DefineConstant[ y_min = {-130000, Name "Box ymin (m, local)"} ];
DefineConstant[ y_max = { 130000, Name "Box ymax (m, local)"} ];
DefineConstant[ z_top = {      0, Name "Free surface elevation (m, local)"} ];
DefineConstant[ z_bot = { -50000, Name "Domain bottom (m, local)"} ];

// --- Mesh sizing (driver overrides via -setnumber) ---
DefineConstant[ res_f       = { 1000, Name "On-fault target edge length (m)"} ];
DefineConstant[ res_ff      = {20000, Name "Far-field edge length (m)"} ];
DefineConstant[ ramp_dist   = {30000, Name "Linear ramp width (m)"} ];
DefineConstant[ tube_radius = { 5000, Name "Uniform near-fault tube radius (m)"} ];

// --- 3-D meshing algorithm.  10 = HXT (preferred for conformal input,
//     enforces internal-face conformity strictly), 4 = Frontal-Delaunay
//     (more permissive for non-conformal multi-fault input but does NOT
//     enforce fault-tet conformity — see PLAN_multifault_intersections
//     §Why this plan exists). ---
DefineConstant[ algo3d      = {   10, Name "Mesh.Algorithm3D (10=HXT, 4=FD)"} ];

// --- Local refinement at cross-fault polyline endpoints (sliver-fix
//     "Option L", 2026-04-30).  When = 1, generate_safs_mesh.py writes
//     `polyline_endpoints.geo` listing every cross-fault polyline
//     endpoint (vertex coord shared by triangles of ≥ 2 different
//     faults) and this script Includes it.  A Distance + Threshold
//     field around those points imposes a smaller mesh size locally,
//     giving HXT more interior vertices to use as wedge-tet apexes
//     and reducing the worst-γ slivers concentrated at fault-fault
//     intersections.  When = 0 (default), behaviour is identical to
//     pre-Option-L: only Field[2] is in effect. ---
DefineConstant[ local_refine = {    0, Name "Polyline-endpoint local refinement (1=on, 0=off)"} ];
DefineConstant[ local_refine_size = { 500, Name "Local refinement min size at polyline endpoints (m)"} ];
DefineConstant[ local_refine_radius = {2000, Name "Local refinement radius (m)"} ];

// --- Bbox-query tolerance (must be << round_to in the driver) ---
eps = 1.0;

// ---------------------------------------------------------------------------
// 1. Bulk volume
// ---------------------------------------------------------------------------
Box(1) = {x_min, y_min, z_bot, x_max - x_min, y_max - y_min, z_top - z_bot};
bulk_vol = 1;

// ---------------------------------------------------------------------------
// 2. Import per-fault STLs.  generate_safs_mesh.py writes safs_includes.geo
//    with one `Merge "<stl_dir>/<short>.stl";` line per included fault.
//    Each Merge produces one discrete surface in the model.
// ---------------------------------------------------------------------------
Include "safs_includes.geo";

// ---------------------------------------------------------------------------
// 3. Identify box faces vs fault surfaces by bounding-box queries.
//    The bulk Box's 6 outer faces are queryable; everything else is a fault.
// ---------------------------------------------------------------------------
xm_box[]   = Surface In BoundingBox{
  x_min - eps, y_min - eps, z_bot - eps,
  x_min + eps, y_max + eps, z_top + eps};
xp_box[]   = Surface In BoundingBox{
  x_max - eps, y_min - eps, z_bot - eps,
  x_max + eps, y_max + eps, z_top + eps};
yp_box[]   = Surface In BoundingBox{
  x_min - eps, y_max - eps, z_bot - eps,
  x_max + eps, y_max + eps, z_top + eps};
ym_box[]   = Surface In BoundingBox{
  x_min - eps, y_min - eps, z_bot - eps,
  x_max + eps, y_min + eps, z_top + eps};
ztop_box[] = Surface In BoundingBox{
  x_min - eps, y_min - eps, z_top - eps,
  x_max + eps, y_max + eps, z_top + eps};
zbot_box[] = Surface In BoundingBox{
  x_min - eps, y_min - eps, z_bot - eps,
  x_max + eps, y_max + eps, z_bot + eps};

box_faces[] = {xm_box[], xp_box[], yp_box[], ym_box[],
               ztop_box[], zbot_box[]};

fault_surfs[] = Surface{:};
fault_surfs[] -= box_faces[];

// ---------------------------------------------------------------------------
// 4. Embed the discrete fault triangulation in the bulk volume as a
//    Steiner constraint.  HXT recovers the fault triangles as internal
//    faces (each triangle ends up shared by exactly two tets, except for
//    triangles whose three vertices lie on the box top, which the
//    free-surface clearance is designed to prevent).
// ---------------------------------------------------------------------------
Surface{fault_surfs[]} In Volume{bulk_vol};

// ---------------------------------------------------------------------------
// 5. Mesh size field — distance from any fault triangle, threshold ramp.
// ---------------------------------------------------------------------------
Field[1] = Distance;
Field[1].SurfacesList = {fault_surfs[]};
// R-404: 200 samples per surface (was 100).  Distance-field sampling
// is per-surface; coarse fault input (e.g., 500 m CFM resolution
// producing < 100 triangles per fault) caused patchy distance fields
// at Sampling=100.  Cost is negligible — distance is computed once.
Field[1].Sampling     = 200;

Field[2] = Threshold;
Field[2].InField  = 1;
// R-401: bias the lower end of the size field by 0.7 to compensate
// for HXT's empirical ~1.4× coarsening factor on open-surface
// constraints.  Without this bias, in-tube tets average 1383 m for
// `res_f = 1000 m` (38 % above target) — see REVIEW_phase3.md
// R-401 for the measurement.  Combined with `Mesh.MeshSizeFactor =
// 0.7` below, the actual post-mesh in-tube tet edge mean lands at
// ~ res_f.
//
// Sliver-fix attempt rejected (2026-04-30, "Option 2a"): tried
// SizeMin = res_f * 0.3 to pack more interior vertices near the
// fault, hoping HXT would prefer 3-fault + 1-interior tets over
// 4-fault wedges.  Result: γ_min unchanged at 1.36×10⁻⁴ (bit
// identical), tet count +18 %, sliver count 195 → 191.  The all-
// fault wedge tet is determined ENTIRELY by the fault triangulation
// (4 fault vertices, no interior vertex involved); refining bulk
// vertex density has no effect on it.  Reverted.  Killing these
// slivers requires modifying fault topology (Option 2b/3/4), not
// the bulk size field.
Field[2].SizeMin  = res_f * 0.7;
Field[2].SizeMax  = res_ff;
// PLAN Phase 3 — tube-uniform near-fault zone:
//   distance ∈ [0, tube_radius]              → size = res_f (uniform tube)
//   distance ∈ [tube_radius, tube_radius+ramp_dist] → linear ramp to res_ff
//   distance > tube_radius+ramp_dist         → size = res_ff (far-field)
// Setting DistMin = 0 (the old behaviour) ramps immediately, which leaves
// no uniform shell around the fault for the friction cohesive zone.
Field[2].DistMin  = tube_radius;
Field[2].DistMax  = tube_radius + ramp_dist;
Field[2].Sigmoid       = 0;
Field[2].StopAtDistMax = 0;

// Option L (2026-04-30): local refinement at cross-fault polyline
// endpoints.  generate_safs_mesh.py writes `polyline_endpoints.geo`
// (defining `pl_pts[]` as a list of Point IDs), included only when
// `local_refine = 1`.  Field[3] = Distance from those points;
// Field[4] = Threshold imposing `local_refine_size` m within
// `local_refine_radius` m of any polyline endpoint, ramping to res_f
// outside; Field[5] = Min(Field[2], Field[4]) — uses the SMALLER
// requested size at every point in the bulk.
//
// This targets the 4-fault-vertex wedge slivers that concentrate
// at fault-fault intersections (~78 slivers in Step 5b for the
// new-set 5-fault build).  Bulk-density refinement uniformly across
// the tube (Field[2].SizeMin) was empirically shown not to help (it
// can't reach all-fault wedge tets).  But denser bulk JUST AT THE
// POLYLINE ENDPOINTS may give HXT enough interior-vertex options to
// avoid those wedges where the dihedral angle is favourable.
If (local_refine == 1)
  Include "polyline_endpoints.geo";
  Field[3] = Distance;
  Field[3].PointsList = {pl_pts[]};
  Field[3].Sampling = 100;

  Field[4] = Threshold;
  Field[4].InField = 3;
  Field[4].SizeMin = local_refine_size;
  // SizeMax must MATCH the surrounding tube size (Field[2]'s SizeMin =
  // res_f * 0.7), so the ramp from SizeMin (at the polyline endpoint)
  // to SizeMax (at DistMax) ends exactly at the tube's nominal mesh
  // size, giving a smooth transition with no discontinuity.  Combined
  // with `StopAtDistMax = 1` below, the field returns SizeMax * (very
  // large) beyond DistMax — effectively "no constraint" — so
  // Field[5] = Min(Field[2], Field[4]) defaults to Field[2] outside
  // the refinement zone.  This is the correct way to add a localized
  // refinement on top of a global background field; setting SizeMax
  // to res_f or res_ff (as I incorrectly tried earlier) either makes
  // the ramp too gentle to actually refine, or leaks far-field
  // densification through the Min when StopAtDistMax = 0.
  Field[4].SizeMax = res_f * 0.7;
  Field[4].DistMin = 0;
  Field[4].DistMax = local_refine_radius;
  Field[4].Sigmoid = 0;
  Field[4].StopAtDistMax = 1;

  Field[5] = Min;
  Field[5].FieldsList = {2, 4};
  Background Field = 5;
EndIf
If (local_refine == 0)
  Background Field = 2;
EndIf


Mesh.MeshSizeExtendFromBoundary = 0;
Mesh.MeshSizeFromPoints         = 0;
Mesh.MeshSizeFromCurvature      = 0;
// R-406: `Mesh.MeshSizeMin` is a SOFT floor, not a hard constraint.
// HXT honours fault-triangle constraints (which can have edges down
// to ~ res_f / 3 near polyline kinks) BEFORE the global size-field
// floor, so in-tube tets adjacent to short fault edges may be
// shorter than this floor.  This is expected behaviour; the floor
// only steers HXT's interior tet generation.
Mesh.MeshSizeMin                = res_f;
Mesh.MeshSizeMax                = res_ff;

// Empirical findings (2026-04-30) from trying to make the local-
// refinement field actually shrink mesh size at the polyline
// endpoints:
//   1. Lowering MeshSizeMin to local_refine_size leaks into the
//      far field via HXT's Delaunay refinement using MeshSizeMin
//      as a Steiner-vertex target — adds 70k+ tets in [10km, inf)
//      band, only +60 tets in [0, 500m) band.
//   2. Keeping MeshSizeMin = res_f means the field's request below
//      res_f is clamped up to res_f globally — the local
//      refinement does nothing visible.
//   3. The [0, 500m) zone near polyline endpoints is ALREADY at
//      mean edge ~ 940m, min edge ~ 170m, because the autorefined
//      fault triangulation imposes sub-200m fault-triangle edges
//      and HXT honors those as hard constraints.  No size-field
//      tuning can push bulk mesh below what the fault triangulation
//      already requires there.
// Conclusion: the `local_refine` flag is implemented correctly at
// the field level but is functionally a NO-OP on this dataset for
// the [0, 500m) zone, and a far-field leak in any other zone.
// Keeping MeshSizeMin = res_f globally avoids the leak; the local-
// refine option is preserved in the .geo for future datasets where
// the polyline-adjacent fault triangulation is coarser.

// R-401: bias the global mesh size by 0.7 so HXT (which empirically
// produces tets ~1.4× the field's request near surface constraints)
// outputs in-tube tets at ~ res_f.  Combined with the 0.7-biased
// Field[2].SizeMin above, the actual mesh size in the tube lands
// within ±15 % of res_f.
//
// Sliver-tune note (2026-04-30): tried Factor=0.5 to reduce slivers;
// it cut sliver count 204→186 (only 9 %) but regressed
// check_11_tube_uniformity (mean 1460 m vs target 2000 m).  The
// dominant sliver source is a bit-zero edge (two coincident vertices)
// in autorefine output, NOT HXT's per-vertex spacing.  Reverted to
// 0.7 and addressing the real cause via post-autorefine vertex
// dedup in tools/corefine_faults.
Mesh.MeshSizeFactor             = 0.7;

Mesh.Algorithm     = 6;     // 2D: Frontal-Delaunay (unchanged)
// 3-D algorithm chosen by the driver via `-setnumber algo3d <N>`.
// Default 10 = HXT, which enforces internal-face conformity strictly
// (every fault triangle becomes a shared tet face).  For non-conformal
// multi-fault input HXT will REJECT with a PLC-recovery error; in
// that case the driver may pass `-setnumber algo3d 4` (Frontal-Delaunay)
// to mesh anyway, accepting that fault triangles will be detached
// from the bulk tets (validator check 5 will fail).
Mesh.Algorithm3D   = algo3d;
// Sliver-tune (2026-04-30): if HXT fails to recover the PLC, fall
// back to Frontal-Delaunay so the build still produces a usable
// mesh (validator check 5 will report which fault tris weren't
// embedded; better than an empty .msh with PLC error).
Mesh.AlgorithmSwitchOnFailure = 1;
Mesh.Optimize           = 1;
Mesh.OptimizeNetgen     = 1;
// R-403: raise OptimizeThreshold from 0.3 to 0.5 to give Netgen's
// post-mesh optimizer a wider window for sliver removal.  At 0.3 the
// optimizer skipped tets in the 0.3-0.5 quality band, leaving slivers
// that affect SEAS DG flux assembly near the fault.
Mesh.OptimizeThreshold  = 0.5;
Mesh.QualityType        = 2;
Mesh.RandomSeed         = 1;
Mesh.MshFileVersion     = 2.2;

// ---------------------------------------------------------------------------
// 6. Physical groups (BP5-compatible).
// ---------------------------------------------------------------------------
Physical Surface("xm",   1) = {xm_box[]};
Physical Surface("xp",   2) = {xp_box[]};
Physical Surface("yp",   3) = {yp_box[]};
Physical Surface("ym",   4) = {ym_box[]};
Physical Surface("ztop", 5) = {ztop_box[]};
Physical Surface("zbot", 6) = {zbot_box[]};

Physical Surface("fault", 100) = fault_surfs[];

Physical Volume("domain", 10) = {Volume{:}};
